name: build-deploy

on:
  push:
    branches:
      - main

env:
  VITE_PHONE_NUMBER: ${{ secrets.VITE_PHONE_NUMBER }}
  VITE_EMAIL: ${{ secrets.VITE_EMAIL }}
  VITE_PUBLIC_URL: https://heilpraktikerin-jana-goellner.de
  VITE_BACKEND_URL: https://heilpraktikerin-jana-goellner.de

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run prepare:deploy

      # we just copy frontend files for now, backend needs manual restart
      # (currently not so often deployed)
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SCP_HOST }}
          username: ${{ vars.SCP_USERNAME }}
          key: ${{ secrets.SCP_KEY }}
          port: ${{ vars.SCP_PORT }}
          source: .deploy
          strip_components: 1
          overwrite: true
          target: /home/bitnami/projects/natural-health-practitioner-jana-goellner
